import OpenWccDiagram from "./diagrams/OpenWccDiagram";
import SviDiagram from "./diagrams/SviDiagram";
import OdooDiagram from "./diagrams/OdooDiagram";
import WebrtcDiagram from "./diagrams/WebrtcDiagram";
import BackupDiagram from "./diagrams/BackupDiagram";

export const CATEGORIES = [
  { key: "tous", label: "Tous" },
  { key: "infra", label: "Système & Réseau" },
  { key: "web", label: "Web" },
];

export const projects = [
  {
    id: "openwcc",
    category: "infra",
    kicker: "flux réel · FreeBSD 14",
    title: "OpenWCC, en train de tourner",
    tagline: "OpenWCC · Ansible · FreeBSD",
    summary: "Un centre de contacts open source déployé derrière un pare-feu PF, entièrement redéployable par playbook Ansible.",
    tags: ["FreeBSD", "Asterisk", "Ansible", "PostgreSQL", "Prometheus"],
    link: "https://github.com/KeNrOm97/OpenWCC",
    linkLabel: "github.com/KeNrOm97/OpenWCC",
    Diagram: OpenWccDiagram,
    paragraphs: [
      "Un centre de contacts, d'habitude, c'est une licence propriétaire et une boîte noire. On m'a demandé d'en construire un avec des briques ouvertes, le tout derrière un pare-feu, sur FreeBSD. La partie dont je suis le plus fier ne se voit pas : chaque brique est écrite dans un playbook Ansible, donc la plateforme entière se redéploie sans intervention manuelle.",
    ],
    figcaption: "Fig. 01. Tous les flux entrants passent par PF avant d'atteindre un service ; les services partagent un même accès aux données. Ansible pose l'ensemble, la supervision le regarde tourner.",
  },
  {
    id: "svi",
    category: "infra",
    kicker: "Python · Asterisk AGI · Cassandra",
    title: "Un appel dans le SVI",
    tagline: "Asterisk · Python AGI · Cassandra",
    summary: "Un serveur vocal interactif dont le routage est décidé à l'exécution, lu et écrit en direct dans Cassandra.",
    tags: ["Asterisk", "Python", "AGI", "Cassandra"],
    link: "https://github.com/KeNrOm97/Asterisk-svi-python-cassandra",
    linkLabel: "github.com/KeNrOm97/Asterisk-svi-python-cassandra",
    Diagram: SviDiagram,
    paragraphs: [
      "Un serveur vocal interactif classique code son routage en dur dans le dialplan : le moindre changement demande une intervention. J'ai écrit le mien en Python, branché sur Asterisk via AGI, avec les données d'appel lues et écrites en direct dans Cassandra. Changer un routage devient une écriture en base, pas une modification de configuration.",
    ],
    figcaption: "Fig. 02. Le seul lien qui compte est en turquoise : la destination remonte du script, pas d'une règle figée dans le dialplan. Changer un routage devient une écriture en base, pas une modification de configuration.",
  },
  {
    id: "odoo",
    category: "infra",
    kicker: "Odoo 18 · Docker Compose",
    title: "Dossiers de subvention",
    tagline: "Odoo 18 · Docker Compose",
    summary: "Un module Odoo 18 qui transforme un dossier de subvention en objet métier suivi, avec circuit de validation par états.",
    tags: ["Odoo 18", "Python", "Docker Compose", "Nginx", "PostgreSQL"],
    link: null,
    linkLabel: null,
    Diagram: OdooDiagram,
    paragraphs: [
      "Un dossier de subvention se monte d'ordinaire à coups de tableurs et de pièces jointes éparpillées, sans trace fiable de qui a validé quoi. Lors d'une mission, j'ai construit un module Odoo 18 qui en fait un vrai objet métier : formulaire unique, justificatifs rattachés, circuit de validation par états, historique conservé.",
      "Le retour en brouillon est la transition qui justifie le module : elle remplace les allers-retours par courriel et garde la trace de ce qui manquait. Odoo, PostgreSQL et Nginx tournent en services séparés sous Docker Compose, addons montés en volume.",
    ],
    figcaption: "Fig. 03. Le retour en brouillon est la transition qui justifie le module : c'est elle qui remplace les allers-retours par courriel et garde la trace de ce qui manquait. Odoo, PostgreSQL et Nginx tournent en services séparés sous Docker Compose, addons montés en volume.",
  },
  {
    id: "webrtc",
    category: "infra",
    kicker: "Asterisk · WebRTC · TLS/SRTP",
    title: "Appeler depuis un navigateur, sans rien installer",
    tagline: "Asterisk · WebRTC · TLS/SRTP",
    summary: "Une passerelle temps réel : signalisation WebSocket sécurisée, média chiffré SRTP, certificats renouvelés seuls.",
    tags: ["Asterisk", "WebRTC", "TLS/SRTP", "Let's Encrypt", "lighttpd"],
    link: null,
    linkLabel: null,
    Diagram: WebrtcDiagram,
    paragraphs: [
      "Une passerelle temps réel qui supprime le logiciel client : signalisation WebSocket sécurisée, flux média chiffrés en SRTP, certificats Let's Encrypt renouvelés tout seuls, servis par lighttpd sur FreeBSD.",
      "Le poste de l'agent n'installe rien : la page arrive de lighttpd, la voix passe chiffrée par le pare-feu jusqu'à Asterisk, qui met en relation avec les postes SIP internes.",
    ],
    figcaption: "Fig. 04. Le poste de l'agent n'installe rien : la page arrive de lighttpd, la voix passe chiffrée par PF jusqu'à Asterisk. Le certificat se renouvelle sans intervention.",
  },
  {
    id: "backup",
    category: "infra",
    kicker: "Shell · tar/gzip · SCP/SSH · cron",
    title: "Une sauvegarde sans prétention, qui tourne seule",
    tagline: "Shell · tar/gzip · SCP/SSH · cron",
    summary: "Compression, transfert SCP, rotation et purge automatiques, déclenchés par cron, sans dépendance à installer.",
    tags: ["Shell", "tar/gzip", "SCP/SSH", "cron"],
    link: "https://github.com/KeNrOm97/Backup-tar-scp",
    linkLabel: "github.com/KeNrOm97/Backup-tar-scp",
    Diagram: BackupDiagram,
    paragraphs: [
      "Pas de logiciel à installer : compression tar.gz, transfert SCP vers un hôte distant, rotation sur deux jours, déclenchement par cron. Pensée pour tourner seule en production et rester lisible par la personne qui me remplacera.",
      "La purge ferme la boucle : sans elle, le disque distant se remplit tout seul. Tar, scp et cron sont déjà là. Aucune dépendance à installer.",
    ],
    figcaption: "Fig. 05. Aucune dépendance à installer : tar, scp et cron sont déjà là. La purge ferme la boucle, sinon le disque distant se remplit tout seul.",
  },
  {
    id: "mirustream",
    category: "web",
    kicker: "Media center",
    title: "MiruStream",
    tagline: "Next.js · Supabase · Vercel",
    summary: "Catalogue, lecture et déploiement continu.",
    tags: ["Next.js", "Supabase", "Vercel"],
    link: "https://kodi-v2.vercel.app/browse",
    linkLabel: "kodi-v2.vercel.app",
    image: "/mirustream.jpg",
    imageAlt: "Page d'accueil de MiruStream",
    paragraphs: ["Catalogue, lecture et déploiement continu."],
  },
  {
    id: "mirustream-api",
    category: "web",
    kicker: "API",
    title: "MiruStream API",
    tagline: "FastAPI · Python · Docker",
    summary: "Backend REST qui alimente MiruStream, livré en conteneur.",
    tags: ["FastAPI", "Python", "Docker"],
    link: null,
    linkLabel: "dépôt privé",
    paragraphs: ["Backend REST qui alimente MiruStream, livré en conteneur."],
  },
  {
    id: "mirulist",
    category: "web",
    kicker: "Catalogue",
    title: "MiruList",
    tagline: "JavaScript · Vercel",
    summary: "Suivi de catalogue et de progression avec interface web.",
    tags: ["JavaScript", "Vercel"],
    link: "https://mywatchlist-ten.vercel.app/",
    linkLabel: "mywatchlist-ten.vercel.app",
    image: "/mirulist.jpg",
    imageAlt: "Page d'accueil de MiruList",
    paragraphs: ["Suivi de catalogue et de progression avec interface web."],
  },
  {
    id: "loup-g",
    category: "web",
    kicker: "Jeu",
    title: "Loup_G",
    tagline: "TypeScript · Vercel",
    summary: "Jeu multijoueur en ligne (loup-garou).",
    tags: ["TypeScript", "Vercel"],
    link: null,
    linkLabel: "en cours",
    paragraphs: ["Jeu multijoueur en ligne (loup-garou)."],
  },
];
